import Link from "next/link";

import { ZoomableInfographic } from "@/components/ZoomableInfographic";
import { chapterInfographicHref, getChapterInfographic } from "@/lib/infographics";
import { chapterHref, type ChapterEntry } from "@/lib/examples";

const cardClass = [
  "rounded-xl border border-black/10 bg-white/60 p-4 shadow-[0_0_0_1px_rgba(0,0,0,0.03)]",
  "dark:border-white/10 dark:bg-zinc-950/30 dark:shadow-[0_0_0_1px_rgba(255,255,255,0.03)]"
].join(" ");

const glassCard = [
  "rounded-2xl border border-black/10 bg-white/70 p-5 shadow-[0_0_0_1px_rgba(0,0,0,0.03)]",
  "dark:border-white/10 dark:bg-zinc-950/30 dark:shadow-[0_0_0_1px_rgba(255,255,255,0.03)]"
].join(" ");

const linkButtonClass = [
  "mt-4 inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm font-medium",
  "border-zinc-300/60 bg-white/80 text-zinc-900 hover:bg-white",
  "dark:border-white/10 dark:bg-zinc-900/70 dark:text-zinc-100 dark:hover:bg-zinc-900",
  "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-black/10 dark:focus-visible:ring-white/20"
].join(" ");

export function InfographicChapterLink({ chapter }: { chapter: ChapterEntry }) {
  const infographic = getChapterInfographic(chapter.number);
  if (!infographic) return null;

  return (
    <section className={cardClass}>
      <h2 className="text-sm font-medium text-zinc-950 dark:text-zinc-100">Chapter infographic</h2>
      <Link href={chapterInfographicHref(chapter.number!)} className={linkButtonClass}>
        View chapter infographic
      </Link>
    </section>
  );
}

export function ChapterInfographicPageView({ chapter }: { chapter: ChapterEntry }) {
  const infographic = getChapterInfographic(chapter.number);
  if (!infographic) return null;

  const alt = `${chapter.name} infographic: ${infographic.title}`;

  return (
    <div className="space-y-8">
      <div className="space-y-3">
        <Link
          href={chapterHref(chapter)}
          className="text-sm text-zinc-600 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-100"
        >
          ← Back to {chapter.name}
        </Link>
        <div>
          <h1 className="text-3xl font-semibold tracking-tight text-zinc-950 dark:text-zinc-50">
            {chapter.name} — Infographic
          </h1>
          <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">
            {infographic.title}
          </p>
        </div>
      </div>

      <section className={glassCard}>
        <div
          className={[
            "rounded-xl border border-amber-300/70 bg-amber-50/90 p-4 text-sm leading-relaxed text-amber-950",
            "dark:border-amber-500/30 dark:bg-amber-950/35 dark:text-amber-100"
          ].join(" ")}
        >
          <p className="font-medium">LLM-generated supplement — please read before using</p>
          <ul className="mt-2 list-disc space-y-1.5 pl-5">
            <li>
              This infographic was generated by an LLM based on the ebook. It is{" "}
              <strong>not</strong> Alan Belkin&apos;s own wording.
            </li>
            <li>
              It is not meant to replace the book, but to supplement it — for example to
              prepare for a study group session or to recap a chapter after reading it.
            </li>
          </ul>
        </div>

        <div className="mt-5">
          <ZoomableInfographic src={infographic.image} alt={alt} />
        </div>
      </section>
    </div>
  );
}
